/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
static yyconst short int yy_accept[225] =
    {   0,
        0,    0,    0,    0,    0,    0,   53,   53,    0,    0,
       62,   58,   59,   60,   58,   58,   31,   44,   25,   58,
       40,   32,   33,   25,   24,   38,   24,   58,   25,   19,
       39,   27,   28,   27,   18,   36,   37,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   34,   58,
       35,   42,   43,   61,   41,   45,   49,   61,   48,   45,
       53,   61,   53,   56,   57,   61,   56,    0,    0,   59,
       60,   27,   30,   29,   26,   23,   20,    0,   54,   50,
        0,   20,   19,   21,   21,   18,   18,   18,   18,   18,
       18,   18,   18,    5,   18,   18,   18,    1,   18,   18,

       18,   18,   18,   18,   43,   49,   46,   47,   53,   53,
       52,    0,   57,   55,    0,    0,   22,   23,    0,   20,
       21,   21,    0,   23,   22,   50,   50,    0,   20,   19,
       21,   21,   21,    0,   20,   18,   18,   18,   18,   18,
       18,   18,   18,   18,    3,    7,   18,   18,   18,   18,
       18,   55,   22,   22,   22,    0,    0,    0,   21,    0,
       20,   22,   22,   22,   51,    0,   21,   20,   20,   21,
       18,   18,   18,   14,    8,   18,   18,   18,    2,   18,
       18,   18,   18,   11,   18,   22,   22,    0,   22,   20,
       20,   21,   22,    0,   22,   21,   20,   21,    0,   18,

        6,   18,   18,   18,    9,   18,   18,   18,    4,   20,
       21,    0,   22,   18,   18,   10,   18,   12,   13,   18,
       15,   17,   16,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    6,    7,    1,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       26,   27,   28,    1,   24,    1,   29,   30,   31,   32,

       33,   34,   24,   35,   36,   24,   37,   38,   24,   39,
       40,   41,   24,   42,   43,   44,   45,   46,   47,   24,
       24,   24,   48,   49,   50,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[51] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    1,
        1,    1,    1,    6,    6,    1,    1,    1,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    1,    1
    } ;

static yyconst short int yy_base[235] =
    {   0,
        0,    0,   48,   49,   57,   58,   52,   63,   64,   67,
      561,   56,   69,  628,   91,   95,   82,   84,   86,  104,
       93,  102,  106,  111,  124,  115,  131,  135,  148,  181,
      126,  213,  214,  215,  144,  146,  224,  225,  226,  235,
      244,  236,  244,   44,  141,  246,  247,  255,  237,  272,
      273,  628,  628,  554,  628,  628,  628,  550,  628,  543,
      511,  628,  296,  628,  628,  532,  510,  277,  295,  311,
      628,  628,  628,  628,  628,  300,  301,  313,  628,  497,
      303,  318,  501,  319,  331,   48,    0,  341,  484,  466,
      477,  456,  349,  446,  445,  447,  442,    0,  436,  437,

       88,  433,  430,  429,  628,  628,  628,  628,  435,  364,
      628,  455,  628,  445,   89,  425,  353,  354,  376,  363,
      424,  383,  159,  384,  387,  413,  371,  321,  388,  420,
      356,  417,  408,  322,  409,  412,  394,  385,  373,  367,
      365,  355,  351,  348,    0,    0,  323,  308,  305,  310,
      293,  322,  413,  416,  431,  400,  342,  391,  289,  434,
      435,  438,  442,  453,  628,  304,  457,  460,  464,  482,
      475,  488,  267,    0,    0,  267,  255,  257,    0,  244,
      228,  222,  222,    0,  219,  486,  493,  223,  496,  497,
      504,  517,  515,  525,  526,  530,  533,  546,  508,  537,

        0,  202,  146,  139,    0,  124,  119,  120,    0,  550,
      551,  554,  555,   97,   97,    0,   53,    0,    0,   58,
        0,    0,    0,  628,  583,  589,  595,  601,   70,  607,
      613,  615,  621,   50
    } ;

static yyconst short int yy_def[235] =
    {   0,
      224,    1,  225,  225,  226,  226,  227,  227,  228,  228,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  229,  224,  224,  229,  229,  229,
      229,   39,   39,   43,   43,   43,   43,   43,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  230,
      231,  224,  231,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  232,  224,  224,  233,
      224,  232,   30,  234,  234,   43,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,

       93,  229,  229,  229,  224,  224,  224,  224,  231,  231,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  232,
      234,  234,  224,  224,  224,  233,  233,  224,  232,   30,
      234,  234,  234,  224,  234,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  224,  224,  224,  224,  224,  224,  224,  234,  224,
      234,  224,  224,  224,  224,  224,  234,  232,  234,  234,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  224,  224,  224,  224,  232,
      234,  234,  224,  224,  224,  234,  232,  234,  224,  229,

      229,  229,  229,  229,  229,  229,  229,  229,  229,  232,
      234,  224,  224,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,    0,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224
    } ;

static yyconst short int yy_nxt[679] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   35,   36,   12,   37,   35,   38,
       39,   40,   41,   42,   35,   43,   35,   35,   35,   35,
       44,   45,   46,   35,   35,   47,   48,   49,   50,   51,
       53,   53,   54,   54,   62,  132,   62,   55,   55,   57,
       57,   58,   58,   59,   59,   62,   65,   62,   66,   65,
       70,   66,   70,   70,   68,   87,   67,   87,   63,   67,
       69,   87,   87,   60,   60,  100,   87,   68,   69,   63,
      223,  222,   70,   69,   70,   70,   70,   71,   70,   70,

       68,   69,   68,   72,   68,  116,   69,  117,   69,   68,
       69,   68,   73,   68,   69,   69,   69,   69,   69,   69,
       68,   87,   68,   69,   68,   69,   69,   69,   69,   68,
       69,  148,   74,   68,   69,   69,   69,   75,   69,   69,
      221,  220,   68,   69,   68,   74,   75,   69,   69,   68,
       69,   76,   74,   77,  219,   69,   69,  218,   69,   78,
       79,  217,   86,   69,   68,   80,   68,   78,   88,   74,
       69,  216,   69,  101,   87,  124,   88,  125,   69,   87,
       69,   81,   81,  215,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   82,   81,   83,

       81,   81,   81,   81,   84,   85,   81,   81,   81,   84,
       84,   84,   84,   85,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   81,   81,
       81,   68,   68,   68,   72,   72,   72,   69,   69,   69,
      214,  189,   68,   86,   86,   69,   69,   69,   69,   88,
       88,  209,  208,   86,   90,   68,   69,   88,   88,   88,
       91,   69,   86,  207,   87,   92,   89,   93,   88,   69,
       87,  206,   87,   96,   94,   97,   88,   98,   87,   87,
       87,   95,   99,   87,   87,   87,  103,  205,   87,  104,
       68,   68,  102,   87,  204,   68,   69,   69,  111,  203,

      112,   69,  202,  201,   69,   69,  165,  159,  115,   69,
      115,  116,   70,  117,   70,   70,   76,   76,  118,  120,
       73,  128,  110,  152,  119,  122,  123,   69,  123,  124,
      185,  125,  119,  122,   76,   69,  129,  131,  116,  128,
      168,  184,  122,  133,  134,   69,  134,  116,  183,  135,
      122,  133,  182,   69,  115,  133,  115,  116,   76,  136,
      158,  181,  115,  133,  115,  116,  111,  136,  112,  154,
       76,  155,  118,  165,  131,  166,  180,  156,  119,   76,
      133,  120,  141,  179,  178,  156,  119,  122,  133,  157,
      110,  157,   76,  177,  158,  122,  160,  127,  160,  124,

       76,  161,  162,  163,   76,  164,  129,   76,  119,  158,
      176,  156,  122,  188,  175,  188,  119,  174,  189,  156,
      122,  115,  173,  115,  116,  154,  167,  169,  154,  116,
      171,  186,  116,  170,  187,  159,  172,  156,  130,  127,
      156,  170,  159,  153,  172,  156,  152,  154,  156,  155,
      124,  163,  190,  191,  124,  156,  193,  111,  124,  192,
      195,  110,  194,  156,  151,  150,  194,  192,  149,  163,
      194,  164,  147,  154,  194,  196,  154,  156,  197,  146,
      154,  192,  169,  145,  198,  156,  144,  143,  170,  192,
      142,  154,  198,  171,  140,  199,  170,  199,  116,  172,

      196,  188,  154,  188,  186,  139,  200,  172,  138,  154,
      156,  187,  116,  163,  155,  210,  137,  156,  156,  130,
      163,  198,  191,  127,  116,  156,  155,  114,  192,  198,
      188,  163,  188,  193,  113,  211,  192,  110,  212,  194,
      212,   76,  163,  213,  195,  108,  154,  194,  196,  154,
      194,  197,  106,  116,  192,  171,  105,  198,  194,  188,
      224,  188,  192,  224,  211,  198,  163,  116,  210,  196,
       76,  124,  213,  164,  198,  224,  224,  224,  224,  224,
      224,  224,  198,   52,   52,   52,   52,   52,   52,   56,
       56,   56,   56,   56,   56,   61,   61,   61,   61,   61,

       61,   64,   64,   64,   64,   64,   64,  107,  224,  107,
      224,  107,  107,  109,  109,  224,  224,  109,  109,  121,
      121,  126,  126,  224,  224,  126,  126,   11,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224
    } ;

static yyconst short int yy_chk[679] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    3,    4,    7,  234,    7,    3,    4,    5,
        6,    5,    6,    5,    6,    8,    9,    8,    9,   10,
       13,   10,   13,   13,   12,  229,    9,   44,    7,   10,
       12,   86,   44,    5,    6,   44,   86,   13,   12,    8,
      220,  217,   15,   13,   15,   15,   16,   16,   16,   16,

       17,   13,   18,   17,   19,  115,   17,  115,   18,   15,
       19,   21,   20,   16,   17,   15,   18,   21,   19,   16,
       22,  101,   20,   15,   23,   21,   22,   16,   20,   24,
       23,  101,   24,   26,   22,   24,   20,   25,   23,   26,
      215,  214,   25,   24,   31,   25,   27,   26,   25,   27,
       31,   28,   27,   28,  208,   27,   25,  207,   31,   28,
       29,  206,   35,   27,   36,   29,   29,   28,   35,   29,
       36,  204,   29,   45,   45,  123,   35,  123,   36,   45,
       29,   30,   30,  203,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,

       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   32,   33,   34,   32,   33,   34,   32,   33,   34,
      202,  188,   37,   38,   39,   32,   33,   34,   37,   38,
       39,  185,  183,   40,   39,   49,   37,   38,   39,   40,
       39,   49,   41,  182,   42,   39,   38,   40,   41,   49,
       42,  181,   43,   42,   40,   42,   41,   43,   43,   46,
       47,   41,   43,   43,   46,   47,   47,  180,   48,   48,
       50,   51,   46,   48,  178,   68,   50,   51,   63,  177,

       63,   68,  176,  173,   50,   51,  166,  159,   69,   68,
       69,   69,   70,   69,   70,   70,   76,   77,   76,   77,
       50,   81,   63,  152,   76,   77,   78,   81,   78,   78,
      151,   78,   76,   77,   82,   81,   82,   84,  134,  128,
      134,  150,   82,   84,   85,  128,   85,   85,  149,   85,
       82,   84,  148,  128,   88,   85,   88,   88,  157,   88,
      157,  147,   93,   85,   93,   93,  110,   93,  110,  117,
      118,  117,  118,  127,  131,  127,  144,  117,  118,  120,
      131,  120,   93,  143,  142,  117,  118,  120,  131,  119,
      110,  119,  119,  141,  119,  120,  122,  127,  122,  122,

      124,  122,  124,  125,  129,  125,  129,  158,  124,  158,
      140,  125,  129,  156,  139,  156,  124,  138,  156,  125,
      129,  133,  137,  133,  133,  135,  133,  135,  136,  153,
      136,  153,  154,  135,  154,  132,  136,  153,  130,  126,
      154,  135,  121,  116,  136,  153,  114,  155,  154,  155,
      160,  161,  160,  161,  162,  155,  162,  112,  163,  161,
      163,  109,  162,  155,  104,  103,  163,  161,  102,  164,
      162,  164,  100,  167,  163,  167,  168,  164,  168,   99,
      169,  167,  169,   97,  168,  164,   96,   95,  169,  167,
       94,  171,  168,  171,   92,  170,  169,  170,  170,  171,

      170,  172,  186,  172,  186,   91,  172,  171,   90,  187,
      186,  187,  189,  190,  189,  190,   89,  187,  186,   83,
      191,  190,  191,   80,  199,  187,  199,   67,  191,  190,
      192,  193,  192,  193,   66,  192,  191,   61,  194,  193,
      194,  194,  195,  194,  195,   60,  196,  193,  196,  197,
      195,  197,   58,  200,  196,  200,   54,  197,  195,  198,
       11,  198,  196,    0,  198,  197,  210,  211,  210,  211,
      212,  213,  212,  213,  210,    0,    0,    0,    0,    0,
        0,    0,  210,  225,  225,  225,  225,  225,  225,  226,
      226,  226,  226,  226,  226,  227,  227,  227,  227,  227,

      227,  228,  228,  228,  228,  228,  228,  230,    0,  230,
        0,  230,  230,  231,  231,    0,    0,  231,  231,  232,
      232,  233,  233,    0,    0,  233,  233,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1805087.l"
#define INITIAL 0
#define CHAR_STATE 1

#define STRING_STATE 2

#define MLINE_COMMENT_STATE1 3

#define MLINE_COMMENT_STATE2 4

#line 9 "1805087.l"

#include<iostream>
#include<fstream>
#include<string>
#include "symbolTable.h"
#include"1805087.tab.h"

using namespace std;

// extern YYSTYPE yylval;
extern ofstream logFile;
extern ofstream errorFile;

extern void errorMessage(string message);

int lineCount = 1;
int errorCount = 0;
int tempLineNo;

string charLiteral;
string lexeme;

ofstream tokenFile;

// SymbolTable symbolTable(7);

string toUpper(string str) {
    string tempStr = "";

    for(int i = 0; i < str.length(); i++) {
        char c = str[i];
        if(c >= 'a' && c <= 'z')
            tempStr.push_back(c - 'a' + 'A');
        else
            tempStr.push_back(c);
        
    }

    return tempStr;
}

void logFoundMessage(string token, string lexeme) {
    // logFile << "Line no. "<< lineCount << ": Token <" << token << "> Lexeme " << lexeme << " found.\n\n";
}

void logFoundMessage(string token, string lexeme, string charLiteral) {
    // logFile << "Line no. "<< lineCount << ": Token <" << token << "> Lexeme " 
    //     << lexeme << " found --> <" << token << ", " << charLiteral << ">\n\n";
}

void logFoundMessage(string token, string lexeme, int lineNo) {
    // logFile << "Line no. "<< lineNo << ": Token <" << token << "> Lexeme " << lexeme << " found.\n\n";
}

void logFoundMessage(string token, string lexeme, string charLiterals, int lineNo) {
    // logFile << "Line no. "<< lineNo << ": Token <" << token << "> Lexeme " 
    //     << lexeme << " found --> <" << token << ", " << charLiterals << ">\n\n";
}

void logErrorMessage(string errorMessage, string symbol) {
    errorCount++;
    // logFile << "Line no. "<< lineCount << ": ERROR: " << errorMessage << " " << symbol << "\n\n";
}

void logErrorMessage(string errorMessage, string symbol, int lineNo) {
    errorCount++;
    logFile << "Line no. "<< lineNo << ": ERROR: " << errorMessage << " " << symbol << "\n\n";
    errorFile << "Line no. "<< lineNo << ": ERROR: " << errorMessage << " " << symbol << "\n\n";
}

void writeTokenFile(string token) {
    // tokenFile << "<" << token << "> ";
}

void writeTokenFile(string token, string charLiteral) {
    // tokenFile << "<" << token << ", " << charLiteral << "> ";
}

char extractChar(string str) {
    char c;

    if(str[0] == '\\') {
        // cout << "In if\n";
        switch(str[1]) {
            case 'n':
                c = '\n';
                break;
            case 't':
                c = '\t';
                break;
            case '\\':
                c = '\\' ;
                break;
            case '\'':
                c = '\'';
                break;
            case 'a':
                c = '\a';
                break;
            case 'f':
                c = '\f';
                break;
            case 'r':
                c = '\r';
                break;
            case 'b':
                c = '\b';
                break;
            case 'v':
                c = '\v';
                break;
            case '0':
                c = '\0';
                break;
            case '"':
                c = '\"';
                break;
            default:
                return -1;
        } 
    } else {
        c = str[0];
    }

    return c;
}

#line 729 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 144 "1805087.l"


#line 894 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 225 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 628 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 146 "1805087.l"
{return IF;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 147 "1805087.l"
{return ELSE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 148 "1805087.l"
{return FOR;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 149 "1805087.l"
{return WHILE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 150 "1805087.l"
{return DO;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 151 "1805087.l"
{return BREAK;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 152 "1805087.l"
{return INT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 153 "1805087.l"
{return CHAR;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 154 "1805087.l"
{return FLOAT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 155 "1805087.l"
{return DOUBLE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 156 "1805087.l"
{return VOID;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 157 "1805087.l"
{return RETURN;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 158 "1805087.l"
{return SWITCH;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 159 "1805087.l"
{return CASE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 160 "1805087.l"
{return DEFAULT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 161 "1805087.l"
{return CONTINUE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 162 "1805087.l"
{return PRINTLN;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 164 "1805087.l"
{
    yylval.symbolInfo = new SymbolInfo(yytext, "ID");
    return ID;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 169 "1805087.l"
{
    yylval.symbolInfo = new SymbolInfo(yytext, "CONST_INT");
    return CONST_INT;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 174 "1805087.l"
{
    yylval.symbolInfo = new SymbolInfo(yytext, "CONST_FLOAT");
    return CONST_FLOAT;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 179 "1805087.l"
{
    errorMessage("Invalid Suffix on number or invalid prefix on ID " + string(yytext));
    yylval.symbolInfo = new SymbolInfo(yytext, "ID");
    return ID;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 184 "1805087.l"
{
    errorMessage("Ill formed number" + string(yytext));

    yylval.symbolInfo = new SymbolInfo(yytext, "CONST_FLOAT");
    return CONST_FLOAT;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 191 "1805087.l"
{
    errorMessage("Too many decimal point for the character sequence " + string(yytext));

    yylval.symbolInfo = new SymbolInfo(yytext, "CONST_FLOAT");
    return CONST_FLOAT;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 198 "1805087.l"
{
    yylval.symbolInfo = new SymbolInfo(yytext, "ADDOP");
    return ADDOP;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 203 "1805087.l"
{
    yylval.symbolInfo = new SymbolInfo(yytext, "MULOP");
    return MULOP;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 208 "1805087.l"
{
    yylval.symbolInfo = new SymbolInfo(yytext, "INCOP");
    return INCOP; 
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 213 "1805087.l"
{
    yylval.symbolInfo = new SymbolInfo(yytext, "RELOP");
    return RELOP;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 218 "1805087.l"
{return ASSIGNOP;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 220 "1805087.l"
{
    yylval.symbolInfo = new SymbolInfo(yytext, "ARITHASSIGNOP");
    return ARITHASSIGNOP;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 225 "1805087.l"
{
    yylval.symbolInfo = new SymbolInfo(yytext, "LOGICOP");
    return LOGICOP;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 230 "1805087.l"
{return NOT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 232 "1805087.l"
{return LPAREN;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 233 "1805087.l"
{return RPAREN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 235 "1805087.l"
{return LCURL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 237 "1805087.l"
{return RCURL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 239 "1805087.l"
{return LTHIRD;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 240 "1805087.l"
{return RTHIRD;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 242 "1805087.l"
{return COMMA;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 244 "1805087.l"
{return SEMICOLON;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 246 "1805087.l"
{
    lexeme = yytext;
    charLiteral = "";
    BEGIN CHAR_STATE;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 252 "1805087.l"
{
    lexeme += yytext;

    if(charLiteral.length() == 0) {    
        errorMessage("Empty character constant " + lexeme);

        lexeme.clear();
        charLiteral.clear();

        BEGIN INITIAL;
    } else if(charLiteral.length() == 1 && charLiteral[0] == '\\') {
        charLiteral += yytext;
    } else if((charLiteral[0] == '\\' && charLiteral.length() == 2) || charLiteral.length() == 1) {
        char c = extractChar(charLiteral);

        if(c == -1) {
            errorMessage("Unknown escape sequence: " + lexeme);
        } else {
            string token = "CONST_CHAR";
            charLiteral = "";
            charLiteral.push_back(c);
            
            // writeTokenFile(token, charLiteral);
            // logFoundMessage(token, lexeme, charLiteral);
        }
        
        lexeme.clear();
        charLiteral.clear();

        BEGIN INITIAL;
    } else if(charLiteral.length() > 1) {
        errorMessage("Multi character constant char " + lexeme);
        
        lexeme.clear();
        charLiteral.clear();

        BEGIN INITIAL;
    }
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 292 "1805087.l"
{
    lexeme += yytext;
    charLiteral += yytext;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 297 "1805087.l"
{
    errorMessage("Unfinished character " + lexeme);
    lineCount++;

    lexeme.clear();
    charLiteral.clear();

    BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(CHAR_STATE):
#line 307 "1805087.l"
{
    errorMessage("Unfinished character " + lexeme);

    lexeme.clear();
    charLiteral.clear();
    // printSummary();
    return 0;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 317 "1805087.l"
{
    tempLineNo = lineCount;
    charLiteral = "";
    lexeme = yytext;
    BEGIN STRING_STATE;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 323 "1805087.l"
{
    charLiteral += yytext;
    lexeme += yytext;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 327 "1805087.l"
{
    lexeme += yytext;
    char c = extractChar(yytext);

    if(c == -1) {
        errorMessage("Unknown escape sequence in string: " + lexeme);

        charLiteral.clear();
        lexeme.clear();

        BEGIN INITIAL;
    } else if(c == '\b') {
        // backspace
        if(charLiteral.length() > 0)
            charLiteral.pop_back();
    } else {
        charLiteral.push_back(c);
    }
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 346 "1805087.l"
{
    lineCount++;
    lexeme += yytext;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 351 "1805087.l"
{
    string token = "STRING";
    lexeme += yytext;
    
    charLiteral = "\"" + charLiteral + "\"";
    // writeTokenFile(token, charLiteral);
    // logFoundMessage(token, lexeme, charLiteral, tempLineNo);
    
    charLiteral.clear();
    lexeme.clear();

    BEGIN INITIAL;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 365 "1805087.l"
{
    lexeme += yytext;
    logErrorMessage("Unterminated string", lexeme, tempLineNo);
    lineCount++;

    lexeme.clear();
    charLiteral.clear();

    BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(STRING_STATE):
#line 376 "1805087.l"
{
    logErrorMessage("Unterminated string", lexeme, tempLineNo);
    // printSummary();
    lexeme.clear();
    charLiteral.clear();
    return 0;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 384 "1805087.l"
{
    //logFoundMessage("COMMENT", yytext);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 388 "1805087.l"
{
    tempLineNo = lineCount;
    lineCount++;
    BEGIN MLINE_COMMENT_STATE1;
    lexeme = yytext;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 395 "1805087.l"
{
    lineCount++;
    lexeme += yytext;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 400 "1805087.l"
{
    lexeme += yytext;
    // logFoundMessage("COMMENT", lexeme, tempLineNo);
    lexeme.clear();
    BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(MLINE_COMMENT_STATE1):
#line 406 "1805087.l"
{
    logErrorMessage("Unterminated comment", lexeme, tempLineNo);
    // printSummary();
    return 0;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 412 "1805087.l"
{
    tempLineNo = lineCount;
    lexeme = yytext;
    BEGIN MLINE_COMMENT_STATE2;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 418 "1805087.l"
{
    lexeme += "*/";
    // logFoundMessage("COMMENT", lexeme, tempLineNo);
    lexeme.clear();
    BEGIN INITIAL;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 425 "1805087.l"
{
    lexeme += yytext;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 429 "1805087.l"
{
    lineCount++;
    lexeme += yytext;
}
	YY_BREAK
case YY_STATE_EOF(MLINE_COMMENT_STATE2):
#line 434 "1805087.l"
{
    logErrorMessage("Unterminated comment", lexeme, tempLineNo);
    // printSummary();
    return 0;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 440 "1805087.l"
{
    // printSummary();
    return 0;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 445 "1805087.l"
{errorMessage("Unrecongnized character " + string(yytext));}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 446 "1805087.l"
{}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 447 "1805087.l"
lineCount++;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 449 "1805087.l"
ECHO;
	YY_BREAK
#line 1499 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 225 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 225 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 224);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 449 "1805087.l"
