/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 88
#define YY_END_OF_BUFFER 89
static yyconst short int yy_accept[201] =
    {   0,
       24,   24,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   89,   87,
        2,    1,   34,   43,   29,   87,   66,   35,   36,   27,
       25,   41,   26,   87,   28,   23,   42,   31,   33,   31,
       86,   86,   39,   40,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   37,   87,   38,   57,   56,   45,
       57,   61,   59,   61,   65,   64,   65,   81,   88,   68,
       67,   67,   69,   85,   85,   83,   82,   82,   80,   70,
       78,   77,   79,   75,   76,   72,   71,   74,   70,   73,
        2,   31,   62,   32,   30,   24,   58,    0,   23,   22,

       22,   86,    0,   24,   86,   86,   86,   86,   86,    5,
       86,   86,   86,    3,   86,   86,   86,   86,   86,   46,
       48,   55,   49,   50,   53,   51,   46,   52,   47,   54,
       44,   60,   63,    0,   84,    0,   21,   21,   22,   22,
        0,   22,   24,   86,   86,   86,   86,   86,   86,   86,
       86,    4,    6,   86,   86,   86,   86,    0,   24,   24,
        0,   22,   86,   17,   14,   86,   86,   86,   11,   86,
       86,   86,    8,   86,   19,    0,   20,    0,   22,   13,
       86,   86,   86,    7,   86,   86,   12,   19,    0,   86,
       86,   15,   16,    9,    0,   86,   10,    0,   18,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   25,   26,   24,
       25,   24,   25,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   25,   24,   24,   24,   24,   24,   24,
       27,   28,   29,    1,   24,    1,   30,   31,   32,   33,

       34,   35,   24,   36,   37,   24,   38,   39,   24,   40,
       41,   24,   24,   42,   43,   44,   45,   46,   47,   24,
       24,   24,   48,   49,   50,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[51] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    1,    3,    3,    1,
        1,    1,    1,    3,    4,    3,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    5,    1,    5
    } ;

static yyconst short int yy_base[211] =
    {   0,
        0,    0,   48,   49,   50,   54,   55,   56,   63,   77,
       86,   94,  103,  147,    0,    0,    0,    0,  350,  351,
       69,  351,  327,   58,  351,  340,  351,  351,  351,  351,
      334,  351,  331,   56,   87,   92,  351,  323,  322,  321,
        0,  101,  351,  351,  300,   87,   53,  122,   74,   67,
      307,  293,  298,  302,  351,  288,  351,  351,  351,  188,
      333,  351,  351,  332,  351,  351,  119,  351,  351,  351,
      351,  351,  351,  351,  155,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      120,  351,  351,  351,  351,  136,  351,   66,  150,  111,

      133,    0,  145,  153,  300,  290,  302,  291,  295,  243,
      244,  245,  243,    0,  240,  239,  245,  241,  235,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  177,  351,  177,  351,  183,  155,  167,
      185,  195,  189,  238,  226,  214,  209,  218,  214,  204,
      201,    0,    0,  177,  176,  182,  173,  206,  217,  221,
      208,  231,  172,    0,    0,  168,  155,  159,    0,  144,
      141,  135,    0,  126,  223,  239,  243,  245,  247,    0,
      104,  103,  105,    0,   92,   91,    0,  251,  255,   56,
       37,    0,    0,    0,  257,   29,    0,  261,    0,  351,

      289,  294,  299,  304,  309,  314,  318,  320,  324,  325
    } ;

static yyconst short int yy_def[211] =
    {   0,
      200,    1,  201,  201,  202,  202,  203,  203,  204,  204,
      205,  205,  206,  206,  206,  206,  206,  206,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  207,  200,  200,  200,  200,
      208,  208,  200,  200,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  200,  200,  200,  200,  200,  200,
       60,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  209,  207,  210,

      210,  208,  200,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  210,  210,
      200,  210,  200,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  200,  200,  200,
      200,  210,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  200,  200,  200,  200,  142,  208,
      208,  208,  208,  208,  208,  208,  208,  200,  200,  208,
      208,  208,  208,  208,  200,  208,  208,  200,  208,    0,

      200,  200,  200,  200,  200,  200,  200,  200,  200,  200
    } ;

static yyconst short int yy_nxt[402] =
    {   0,
       20,   21,   22,   21,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   36,   37,
       38,   39,   40,   41,   41,   42,   43,   20,   44,   41,
       45,   46,   47,   48,   49,   41,   50,   41,   41,   41,
       41,   51,   52,   41,   41,   53,   54,   55,   56,   57,
       59,   59,   63,   60,   60,   64,   63,   66,   66,   64,
       67,   67,  199,   93,   69,   70,   67,   67,   71,   93,
       91,   72,   91,   96,   96,   61,   61,   64,   69,   70,
      197,   64,   71,  138,  138,   72,  109,   75,   76,   75,
       73,   77,   93,  110,   78,   75,   76,   75,   93,   77,

      196,  114,   78,   97,   73,   79,  115,   98,   80,   99,
       99,   81,  112,  103,  113,  103,  106,  101,  104,  104,
       82,   91,  107,   91,  133,  101,  194,  108,  139,  139,
       83,  193,   84,   85,  103,  133,  103,   86,  192,  104,
      104,  191,   87,  190,   88,  141,   89,  141,   90,   79,
      142,  142,   80,   96,   96,   81,  134,  135,  134,  187,
      111,  136,  143,  143,   82,   98,  186,   99,   99,  136,
      104,  104,  139,  139,   83,  101,   84,   85,  134,  135,
      134,   86,  185,  101,  139,  139,   87,  184,   88,  103,
       89,  103,   90,  120,  143,  143,  121,  183,  158,  182,

      159,  159,  160,  160,  181,  122,  143,  143,  136,  180,
      161,  174,  142,  142,  173,  123,  136,  124,  125,  172,
      162,  171,  126,  175,  175,  177,  177,  127,  162,  128,
      170,  129,  158,  130,  159,  159,  161,  169,  160,  160,
      188,  188,  136,  178,  168,  178,  176,  167,  179,  179,
      136,  178,  166,  178,  176,  165,  189,  189,  161,  164,
      177,  177,  189,  189,  179,  179,  195,  163,  188,  188,
      161,  157,  189,  189,  198,  198,  158,  156,  198,  198,
      176,  155,  154,  153,  152,  151,  150,  149,  176,   58,
       58,   58,   58,   58,   62,   62,   62,   62,   62,   65,

       65,   65,   65,   65,   68,   68,   68,   68,   68,   74,
       74,   74,   74,   74,   69,   69,   69,   69,   69,  100,
      100,  100,  102,  102,  137,  137,  137,  140,  140,  148,
      147,  146,  145,  144,  132,  131,   94,  119,  118,  117,
      116,  105,   92,   92,   92,   95,   95,   94,   92,  200,
       19,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,

      200
    } ;

static yyconst short int yy_chk[402] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    5,    3,    4,    5,    6,    7,    8,    6,
        7,    8,  196,   24,    9,    9,    7,    8,    9,   24,
       21,    9,   21,   34,   34,    3,    4,    5,   10,   10,
      191,    6,   10,   98,   98,   10,   47,   11,   11,   11,
        9,   11,   35,   47,   11,   12,   12,   12,   35,   12,

      190,   50,   12,   35,   10,   13,   50,   36,   13,   36,
       36,   13,   49,   42,   49,   42,   46,   36,   42,   42,
       13,   91,   46,   91,   67,   36,  186,   46,  100,  100,
       13,  185,   13,   13,   48,   67,   48,   13,  183,   48,
       48,  182,   13,  181,   13,  101,   13,  101,   13,   14,
      101,  101,   14,   96,   96,   14,   75,   75,   75,  174,
       48,   96,  103,  103,   14,   99,  172,   99,   99,   96,
      104,  104,  139,  139,   14,   99,   14,   14,  134,  134,
      134,   14,  171,   99,  140,  140,   14,  170,   14,  136,
       14,  136,   14,   60,  136,  136,   60,  168,  138,  167,

      138,  138,  141,  141,  166,   60,  143,  143,  138,  163,
      142,  157,  142,  142,  156,   60,  138,   60,   60,  155,
      142,  154,   60,  158,  158,  161,  161,   60,  142,   60,
      151,   60,  159,   60,  159,  159,  160,  150,  160,  160,
      175,  175,  159,  162,  149,  162,  160,  148,  162,  162,
      159,  176,  147,  176,  160,  146,  176,  176,  177,  145,
      177,  177,  178,  178,  179,  179,  188,  144,  188,  188,
      189,  119,  189,  189,  195,  195,  198,  118,  198,  198,
      189,  117,  116,  115,  113,  112,  111,  110,  189,  201,
      201,  201,  201,  201,  202,  202,  202,  202,  202,  203,

      203,  203,  203,  203,  204,  204,  204,  204,  204,  205,
      205,  205,  205,  205,  206,  206,  206,  206,  206,  207,
      207,  207,  208,  208,  209,  209,  209,  210,  210,  109,
      108,  107,  106,  105,   64,   61,   56,   54,   53,   52,
       51,   45,   40,   39,   38,   33,   31,   26,   23,   19,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,

      200
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1805092lex.l"
#define INITIAL 0
#define string_state_start 1

#define comment_start 2

#define multicomment_start 3

#define const_char_start 4

#define const_char_end 5

#define const_special_char_start 6

#define multichar 7

#define multichar_end 8

#line 13 "1805092lex.l"
#include <bits/stdc++.h>
#include "SymbolTable.h"

int line_count=1;
int store_line_count;
int error_count=0;
SymbolTable ST{7};
ofstream logout;
ofstream tokenout;

string log_char1="";
string token_char1="";

string log_st1="";
string token_st1="";

string log_comm1="";
string log_multi="";

#line 559 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 44 "1805092lex.l"


#line 713 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 201 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 351 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 46 "1805092lex.l"
{line_count++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 47 "1805092lex.l"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 51 "1805092lex.l"
{
			tokenout<<"<IF> ";
			logout<<"Line no : "<<line_count<<" TOKEN <IF> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 56 "1805092lex.l"
{
			tokenout<<"<FOR> ";
			logout<<"Line no :"<<line_count<<" TOKEN <FOR> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "1805092lex.l"
{
			tokenout<<"<DO> ";
			logout<<"Line no :"<<line_count<<" TOKEN <DO> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 67 "1805092lex.l"
{
			tokenout<<"<INT> ";
			logout<<"Line no :"<<line_count<<" TOKEN <INT> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 72 "1805092lex.l"
{
			tokenout<<"<FLOAT> ";
			logout<<"Line no :"<<line_count<<" TOKEN <FLOAT> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 77 "1805092lex.l"
{
			tokenout<<"<VOID> ";
			logout<<"Line no : "<<line_count<<" TOKEN <VOID> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 82 "1805092lex.l"
{
			tokenout<<"<SWITCH> ";
			logout<<"Line no : "<<line_count<<" TOKEN <SWITCH> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 87 "1805092lex.l"
{
			tokenout<<"<DEFAULT> ";
			logout<<"Line no : "<<line_count<<" TOKEN <DEFAULT> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 93 "1805092lex.l"
{
			tokenout<<"<ELSE> ";
			logout<<"Line no : "<<line_count<<" TOKEN <ELSE> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 99 "1805092lex.l"
{
			tokenout<<"<WHILE> ";
			logout<<"Line no : "<<line_count<<" TOKEN <WHILE> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 104 "1805092lex.l"
{
			tokenout<<"<BREAK> ";
			logout<<"Line no : "<<line_count<<" TOKEN <BREAK> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 109 "1805092lex.l"
{
			tokenout<<"<CHAR> ";
			logout<<"Line no : "<<line_count<<" TOKEN <CHAR> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 115 "1805092lex.l"
{
			tokenout<<"<DOUBLE> ";
			logout<<"Line no : "<<line_count<<" TOKEN <DOUBLE> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 121 "1805092lex.l"
{
			tokenout<<"<RETURN> ";
			logout<<"Line no : "<<line_count<<" TOKEN <RETURN> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 126 "1805092lex.l"
{
			tokenout<<"<CASE> ";
			logout<<"Line no : "<<line_count<<" TOKEN <CASE> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 131 "1805092lex.l"
{
			tokenout<<"<CONTINUE> ";
			logout<<"Line no : "<<line_count<<" TOKEN <CONTINUE> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 138 "1805092lex.l"
{

		logout << "Error at line no " <<line_count<< ": " << "Too Many Decimal Points :" <<  yytext << endl;
		logout << endl;
		error_count++;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 144 "1805092lex.l"
{

		logout << "Error at line no " <<line_count<< ": " << "Ill formed number :" <<  yytext << endl;
		logout << endl;
		error_count++;

}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 151 "1805092lex.l"
{
			logout<<"Error at line no "<<line_count<<": Ill Formed Number "<<yytext<<endl;
			error_count++;
			BEGIN INITIAL;
		}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 159 "1805092lex.l"
{
		logout << "Error at line no " <<line_count<< ": " << "Invalid prefix on ID or invalid suffix on Number:" <<  yytext << endl;
		logout << endl;
		error_count++;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 167 "1805092lex.l"
{
			tokenout<<"<CONST_INT, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <CONST_INT> Lexeme "<<yytext<<" found\n"<<endl;
			bool flag= ST.Insert(yytext, "CONST_INT" );

			if(flag==true){
				string print= ST.printAllScopeTable();
                logout<<print;
                logout<<endl;
				//insert in symbol table and print symbol table content(only non empty buckets)
}
			else if(flag==false)
			{
				logout<<yytext<<" already exists in current ScopeTable"<<endl;
				logout<<endl;
			}
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 184 "1805092lex.l"
{
			tokenout<<"<CONST_FLOAT, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <CONST_FLOAT> Lexeme "<<yytext<<" found\n"<<endl;
				bool flag= ST.Insert(yytext, "CONST_FLOAT" );

			if(flag==true){
				string print= ST.printAllScopeTable();
                logout<<print;
                logout<<endl;
				//insert in symbol table and print symbol table content(only non empty buckets)
			}
			else if(flag==false)
			{
				logout<<yytext<<" already exists in current ScopeTable"<<endl;
				logout<<endl;
			}
			}
	YY_BREAK
case 25:
#line 205 "1805092lex.l"
case 26:
YY_RULE_SETUP
#line 205 "1805092lex.l"
{
			tokenout<<"<ADDOP, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <ADDOP> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 27:
#line 211 "1805092lex.l"
case 28:
#line 212 "1805092lex.l"
case 29:
YY_RULE_SETUP
#line 212 "1805092lex.l"
{
			tokenout<<"<MULOP, " <<yytext<<">";
			logout<<"Line no :  "<<line_count<<" TOKEN <MULOP> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 217 "1805092lex.l"
{
			tokenout<<"<INCOP, " <<yytext<<">";
			logout<<"Line no :  "<<line_count<<" TOKEN <INCOP> Lexeme "<<yytext<<" found\n"<<endl;

		}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 222 "1805092lex.l"
{
			tokenout<<"<RELOP, " <<yytext<<">";
			logout<<"Line no :  "<<line_count<<" TOKEN <RELOP> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 228 "1805092lex.l"
{
			tokenout<<"<LOGICOP, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <LOGICOP> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 233 "1805092lex.l"
{
			tokenout<<"<ASSIGNOP, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <ASSIGNOP> Lexeme "<<yytext<<" found\n"<<endl;
		}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 238 "1805092lex.l"
{
			tokenout<<"<NOT, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <NOT> Lexeme "<<yytext<<" found\n"<<endl;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 243 "1805092lex.l"
{
			tokenout<<"<LPAREN, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <LPAREN> Lexeme "<<yytext<<" found\n"<<endl;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 248 "1805092lex.l"
{
			tokenout<<"<RPAREN, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <RPAREN> Lexeme "<<yytext<<" found\n"<<endl;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 253 "1805092lex.l"
{
			tokenout<<"<LCURL, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <LCURL> Lexeme "<<yytext<<" found\n"<<endl;
			ST.EnterScope();
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 260 "1805092lex.l"
{
			tokenout<<"<RCURL, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <RCURL> Lexeme "<<yytext<<" found\n"<<endl;
			ST.ExitScope();
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 265 "1805092lex.l"
{
			tokenout<<"<LTHIRD, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <LTHIRD> Lexeme "<<yytext<<" found\n"<<endl;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 270 "1805092lex.l"
{
			tokenout<<"<RTHIRD, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <RTHIRD> Lexeme "<<yytext<<" found\n"<<endl;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 275 "1805092lex.l"
{
			tokenout<<"<COMMA, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <COMMA> Lexeme "<<yytext<<" found\n"<<endl;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 280 "1805092lex.l"
{
			tokenout<<"<SEMICOLON, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <SEMICOLON> Lexeme "<<yytext<<" found\n"<<endl;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 287 "1805092lex.l"
{
		log_st1="\"";
		token_st1="\"";
		store_line_count=line_count;
		BEGIN string_state_start;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 294 "1805092lex.l"
{
		log_st1+="\\";
		log_st1+="\n";
		//store_line_count=line_count;
		line_count++;



}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 306 "1805092lex.l"
{

		token_st1+="\"";
		log_st1+="\"";
		tokenout<<"<STRING, " <<token_st1<<">";
		logout<<"Line no : "<<store_line_count<<" TOKEN <STRING> Lexeme "<<log_st1<<" found --> <STRING, "<<token_st1<<">"<<endl;
		BEGIN INITIAL;

}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 319 "1805092lex.l"
{
		log_st1+=yytext;
		token_st1+="\n";

		//store_line_count=line_count;
		line_count++;


}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 329 "1805092lex.l"
{
		log_st1+=yytext;
		token_st1+="\t";



}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 338 "1805092lex.l"
{
		log_st1+=yytext;
		token_st1+="\'";



}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 346 "1805092lex.l"
{
		log_st1+=yytext;
		token_st1+="\\";



}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 355 "1805092lex.l"
{
		log_st1+=yytext;
		token_st1+="a";




}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 364 "1805092lex.l"
{
		log_st1+=yytext;
		token_st1+="\f";



}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 373 "1805092lex.l"
{
		log_st1+=yytext;
		token_st1+="\r";



}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 381 "1805092lex.l"
{
		log_st1+=yytext;
		token_st1+="\b";



}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 389 "1805092lex.l"
{
		log_st1+=yytext;
		token_st1+="\v";



}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 397 "1805092lex.l"
{
		log_st1+=yytext;
		token_st1+="\0";



}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 407 "1805092lex.l"
{
		log_st1+=yytext;
		logout << "Error at line no " <<store_line_count<< ": " << " Unterminated string : " <<  log_st1 << endl;
		logout << endl;
		error_count++;
		line_count++;
		BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(string_state_start):
#line 416 "1805092lex.l"
{
		log_st1+=yytext;
		logout << "Error at line no " <<store_line_count<< ": " << " Unterminated	 string : " <<  log_st1 << endl;
		logout << endl;
		error_count++;
		//line_count++;
		BEGIN INITIAL;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 424 "1805092lex.l"
{
		log_st1+=yytext;
		token_st1+=yytext;

}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 430 "1805092lex.l"
{
		log_comm1="//";

		BEGIN comment_start;
		store_line_count=line_count;

	}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 439 "1805092lex.l"
{

		logout<<"Line no : "<<line_count<<" TOKEN <COMMENT> Lexeme "<<log_comm1<<" found >"<<endl;
		line_count++;
		BEGIN INITIAL;
		//line_count++;


}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 449 "1805092lex.l"
{
		log_comm1+="\\";
		log_comm1+="\n";
		line_count++;
		BEGIN comment_start;

}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 457 "1805092lex.l"
{
		log_comm1+=yytext;
		BEGIN comment_start;

}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 464 "1805092lex.l"
{
		log_multi="/*";
		store_line_count=line_count;
		BEGIN multicomment_start;


	}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 473 "1805092lex.l"
{
		log_multi+=yytext;
		logout<<"Line no : "<<store_line_count<<" TOKEN <COMMENT> Lexeme "<<log_multi<<" found >"<<endl;
		//line_count++;
		BEGIN INITIAL;

}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 481 "1805092lex.l"
{
		log_multi+="\n";
		line_count++;

}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 487 "1805092lex.l"
{
		log_multi+=yytext;

}
	YY_BREAK
case YY_STATE_EOF(multicomment_start):
#line 491 "1805092lex.l"
{
		log_multi+=yytext;
		logout << "Error at line no " <<store_line_count<< ": " << " Unterminated comment : " <<  log_multi << endl;
		logout << endl;
		error_count++;
		//line_count++;
		BEGIN INITIAL;

}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 502 "1805092lex.l"
{
	log_char1+=yytext;
	BEGIN const_char_start;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 507 "1805092lex.l"
{
		log_char1+=yytext;
		logout << "Error at line no " <<line_count<< ": " << " Empty character constant error: " <<  log_char1 << endl;
		logout << endl;
		error_count++;
		//line_count++;
		BEGIN INITIAL;

}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 518 "1805092lex.l"
{

		log_char1+=yytext;
		logout << "Error at line no " <<line_count<< ": " << " Unterminated character : " <<  log_char1 << endl;
		logout << endl;
		error_count++;
		log_char1="";
		line_count++;
		BEGIN INITIAL;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 529 "1805092lex.l"
{
	log_char1+=yytext;
	BEGIN const_special_char_start;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 536 "1805092lex.l"
{
	log_char1+=yytext;
	token_char1='\t';
	BEGIN const_char_end;

}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 542 "1805092lex.l"
{
	log_char1+=yytext;
		token_char1="\n";
	BEGIN const_char_end;

}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 549 "1805092lex.l"
{
	log_char1+=yytext;
		token_char1='\f';
	BEGIN const_char_end;

}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 556 "1805092lex.l"
{
	log_char1+=yytext;
		token_char1='\v';
	BEGIN const_char_end;

}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 563 "1805092lex.l"
{
	log_char1+=yytext;
		token_char1='\r';
	BEGIN const_char_end;

}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 570 "1805092lex.l"
{
	log_char1+=yytext;
		token_char1='\a';
	BEGIN const_char_end;

}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 578 "1805092lex.l"
{
	log_char1+=yytext;
		token_char1='\b';
	BEGIN const_char_end;

}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 585 "1805092lex.l"
{
	log_char1+=yytext;
		token_char1='\0';
	BEGIN const_char_end;


}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 594 "1805092lex.l"
{
	log_char1+=yytext;
		token_char1='\'';
	BEGIN const_char_end;


}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 602 "1805092lex.l"
{
	log_char1+=yytext;
		token_char1='\\';
	BEGIN const_char_end;


}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 609 "1805092lex.l"
{
	log_char1+=yytext;
	line_count++;
	BEGIN const_char_end;


}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 618 "1805092lex.l"
{
	log_char1+=yytext;
	token_char1+=yytext;
	BEGIN const_char_end;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 627 "1805092lex.l"
{
	log_char1+=yytext;
	logout<<"Line no : "<<line_count<<" TOKEN <CONST_CHAR> Lexeme "<<log_char1<<" found --> <CONST_CHAR, "<<token_char1<<">"<<endl;
	tokenout<<"<CONST_CHAR, " <<token_char1<<">";
	bool flag= ST.Insert(log_char1, "CONST_CHAR" );

			if(flag==true){
				string print= ST.printAllScopeTable();
                logout<<print;
                logout<<endl;
				//insert in symbol table and print symbol table content(only non empty buckets)
}
			else if(flag==false)
			{
				logout<<log_char1<<" already exists in current ScopeTable"<<endl;
				logout<<endl;
			}

	log_char1="";
	BEGIN INITIAL;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 651 "1805092lex.l"
{

		log_char1+=yytext;
		logout << "Error at line no " <<line_count<< ": " << " unterminated character : " <<  log_char1 << endl;
		logout << endl;
		error_count++;
		log_char1="";
		line_count++;
		BEGIN INITIAL;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 662 "1805092lex.l"
{

		log_char1+=yytext;
		logout << "Error at line no " <<line_count<< ": " << " unterminated character : " <<  log_char1 << endl;
		logout << endl;
		error_count++;
		log_char1="";
		line_count++;
		BEGIN INITIAL;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 672 "1805092lex.l"
{
		log_char1+=yytext;
		logout << "Error at line no " <<line_count<< ": " << " multi constant error : " <<  log_char1 << endl;
		logout << endl;
		error_count++;
		log_char1="";
		//line_count++;
		BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(const_char_end):
#line 682 "1805092lex.l"
{

		log_char1+=yytext;
		logout << "Error at line no " <<line_count<< ": " << " unterminated character : " <<  log_char1 << endl;
		logout << endl;
		error_count++;
		log_char1="";
	//	line_count++;
		BEGIN INITIAL;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 699 "1805092lex.l"
{
			tokenout<<"<ID, " <<yytext<<">";
			logout<<"Line no : "<<line_count<<" TOKEN <ID> Lexeme "<<yytext<<" found\n"<<endl;

			bool flag= ST.Insert(yytext, "ID" );

			if(flag==true){
				string print= ST.printAllScopeTable();
                logout<<print;
                logout<<endl;
				//insert in symbol table and print symbol table content(only non empty buckets)
}
			else if(flag==false)
			{
				logout<<yytext<<" already exists in current ScopeTable"<<endl;
				logout<<endl;
			}
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment_start):
case YY_STATE_EOF(const_char_start):
case YY_STATE_EOF(const_special_char_start):
case YY_STATE_EOF(multichar):
case YY_STATE_EOF(multichar_end):
#line 718 "1805092lex.l"
{
	logout<<ST.printAllScopeTable();
	logout<<endl;
	logout<<"Total lines: "<<line_count-1<<endl;
	logout<<"Total errors :" << error_count<<endl;
	return 0;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 726 "1805092lex.l"
{
	logout << "Error at line no " <<line_count<< ": " << " unrecognized character : "<<yytext <<endl;
	logout<<endl;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 732 "1805092lex.l"
ECHO;
	YY_BREAK
#line 1715 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 201 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 201 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 200);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 732 "1805092lex.l"


int main(int argc,char *argv[]){

	if(argc!=2){
		cout<<"Please provide input file name and try again\n";
		return 0;
	}

	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		cout<<"Cannot open specified file\n";
		return 0;
	}

	logout.open("log.txt");
	tokenout.open("token.txt");

	yyin= fin;
	yylex();
	fclose(yyin);
	tokenout.close();
	logout.close();

	return 0;
}
