/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
static yyconst short int yy_accept[174] =
    {   0,
        6,    6,    0,    0,    0,    0,    0,    0,    0,    0,
       67,   65,    1,    2,    1,   31,   40,   26,   65,   10,
       32,   33,   25,   38,   25,    8,   26,    5,   39,   28,
       29,   28,    4,    4,   36,   37,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,   34,   65,   35,   24,
       22,   24,   23,   24,   56,   54,   56,   55,   56,   60,
       59,   60,   60,   64,   63,   64,   64,    1,    2,   28,
       30,   27,    6,    8,   61,   57,    8,    5,    9,    9,
        4,    0,    8,    4,    4,    4,    4,    4,    4,    3,
        4,    4,    4,    3,    4,    4,    4,    4,    4,   22,

       14,   15,   21,   13,   16,   19,   17,   11,   18,   12,
       20,   54,   53,    0,   44,   45,   51,   43,   46,   49,
       47,   41,   48,   42,   50,   59,   58,    0,   63,   62,
        7,    6,    0,    8,    8,    8,    0,    6,    8,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,   52,    7,    7,    8,    4,    4,    4,    4,    4,
        4,    4,    4,    7,    4,    4,    4,    4,    4,    4,
        4,    4,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       26,   27,   28,    1,   24,    1,   29,   30,   31,   32,

       33,   34,   24,   35,   36,   24,   37,   38,   24,   39,
       40,   24,   24,   41,   42,   43,   44,   45,   46,   24,
       24,   24,   47,   48,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[50] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    1,    3,    3,    1,
        1,    1,    1,    3,    3,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static yyconst short int yy_base[180] =
    {   0,
        0,    0,   47,   49,   51,   56,   60,   62,   65,   67,
      288,  289,   71,  289,   78,  265,  289,  289,  278,  289,
      289,  289,  272,  289,  269,   66,   55,   76,  289,  261,
      260,  259,    0,   87,  289,  289,  239,   75,   53,  241,
       50,   73,  245,  231,  236,  240,  289,  226,  289,  289,
      289,  270,  289,  110,  289,  289,  269,  289,  153,  289,
      289,  268,   93,  289,  289,  267,  252,  109,  289,  289,
      289,  289,  102,  145,  289,  289,  105,  151,  113,  159,
        0,  127,  107,  121,  235,  225,  237,  226,  230,  219,
      220,  221,  219,    0,  216,  215,  221,  220,  219,  289,

      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  251,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  250,  289,  289,
      170,  181,  189,  193,  123,  197,  201,  205,  129,  223,
      218,  193,  187,  197,  192,  185,  181,  159,  158,  163,
      155,  289,  209,  213,  147,  154,  154,  141,  143,  136,
      132,  137,  121,  217,  113,  112,  100,   83,   82,   70,
       65,   65,  289,  236,  239,  242,  245,  247,   58
    } ;

static yyconst short int yy_def[180] =
    {   0,
      173,    1,  174,  174,  175,  175,  176,  176,  177,  177,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  178,  173,  173,
      173,  173,  179,  179,  173,  173,  179,  179,  179,   34,
      179,  179,  179,  179,  179,  179,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  178,  178,  178,
      179,  173,  173,   34,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  173,

      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  173,  173,  173,  173,  179,  179,  179,  179,  179,
      179,  179,  179,  173,  179,  179,  179,  179,  179,  179,
      179,  179,    0,  173,  173,  173,  173,  173,  173
    } ;

static yyconst short int yy_nxt[339] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   18,   23,   24,   25,   26,   27,   28,   28,   29,
       30,   31,   32,   33,   34,   35,   12,   36,   33,   37,
       38,   39,   40,   41,   33,   42,   33,   33,   33,   33,
       43,   44,   33,   33,   45,   46,   47,   48,   49,   51,
       52,   51,   52,   56,   57,   53,   58,   53,   56,   57,
       81,   58,   61,   62,   61,   62,   75,   65,   66,   65,
       66,   76,   68,   54,   68,   54,   67,   59,   67,   68,
       69,   68,   59,   73,   73,   89,   63,   92,   63,   93,
       74,   77,   90,   78,   78,  127,  128,   94,   74,   82,

       80,   82,   83,   86,   84,   84,   94,   94,   80,   87,
       68,   95,   68,  172,   88,  101,   94,  131,  102,  132,
      132,   94,   73,   73,  139,  139,  133,  103,  173,   74,
      173,  173,   94,  173,  133,  173,  104,   74,  105,  106,
      155,  155,   83,  107,  138,  138,  139,  139,  108,  171,
      109,  170,  110,   94,  111,  113,  114,  134,  115,  134,
      135,  116,  136,  136,  155,  155,   77,  169,   78,   78,
      117,   82,  168,   82,   83,   80,  137,  137,   94,  118,
      167,  119,  120,   80,  166,  153,  121,  154,  154,  165,
       94,  122,  163,  123,   94,  124,  131,  125,  132,  132,

      162,   82,  161,   82,   83,  133,  137,  137,  135,  160,
      136,  136,  135,  133,  136,  136,   83,   94,  137,  137,
       83,  159,  138,  138,  153,  158,  164,  164,  153,  157,
      154,  154,  153,   94,  164,  164,   50,   50,   50,   55,
       55,   55,   60,   60,   60,   64,   64,   64,   79,   79,
       94,  156,  127,  152,  151,  150,  149,  148,   94,   94,
      147,  146,  145,  144,  143,  142,  141,  140,  130,  129,
      126,  112,  100,   71,   99,   98,   97,   96,   91,   85,
       70,   70,   70,   72,   72,   71,   70,  173,   11,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,

      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173
    } ;

static yyconst short int yy_chk[339] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    4,    4,    5,    5,    3,    5,    4,    6,    6,
      179,    6,    7,    7,    8,    8,   27,    9,    9,   10,
       10,   27,   13,    3,   13,    4,    9,    5,   10,   15,
       15,   15,    6,   26,   26,   39,    7,   41,    8,   41,
       26,   28,   39,   28,   28,   63,   63,  172,   26,   34,

       28,   34,   34,   38,   34,   34,   42,  171,   28,   38,
       68,   42,   68,  170,   38,   54,  169,   73,   54,   73,
       73,  168,   77,   77,   83,   83,   73,   54,   79,   77,
       79,   79,  167,   84,   73,   84,   54,   77,   54,   54,
      135,  135,   82,   54,   82,   82,  139,  139,   54,  166,
       54,  165,   54,  163,   54,   59,   59,   74,   59,   74,
       74,   59,   74,   74,  155,  155,   78,  162,   78,   78,
       59,   80,  161,   80,   80,   78,   80,   80,  160,   59,
      159,   59,   59,   78,  158,  131,   59,  131,  131,  157,
      156,   59,  151,   59,  150,   59,  132,   59,  132,  132,

      149,  133,  148,  133,  133,  132,  133,  133,  134,  147,
      134,  134,  136,  132,  136,  136,  137,  146,  137,  137,
      138,  145,  138,  138,  153,  144,  153,  153,  154,  143,
      154,  154,  164,  142,  164,  164,  174,  174,  174,  175,
      175,  175,  176,  176,  176,  177,  177,  177,  178,  178,
      141,  140,  128,  114,   99,   98,   97,   96,   95,   93,
       92,   91,   90,   89,   88,   87,   86,   85,   67,   66,
       62,   57,   52,   48,   46,   45,   44,   43,   40,   37,
       32,   31,   30,   25,   23,   19,   16,   11,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,

      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1805093.l"
#define INITIAL 0
#define CHAR 1

#define STR 2

#define S_CMNT 3

#define M_CMNT 4

#line 9 "1805093.l"
#include <bits/stdc++.h>
#include "SymbolTable.h"
using namespace std;

SymbolTable st(7);
ofstream logOut;
ofstream tokenOut;

unsigned long lineNo = 1;
unsigned long startLineNo;
unsigned long errorNo = 0;
string currentChar;
string currentExactChar;
string currentStr;
string currentExactStr;
string curr;
string currExact;

string toUpper(string s) {
    for (int i = 0; i < s.length(); i++) {
        s[i] = toupper(s[i]);
    }
    return s;
}

#line 530 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 42 "1805093.l"

#line 683 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 174 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 289 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 43 "1805093.l"
{
    // ignore whitespace
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 46 "1805093.l"
{
    lineNo++;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 49 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <" + toUpper(yytext) + "> Lexeme " << yytext << " found" << endl;
    tokenOut << "<" + toUpper(yytext) + "> ";
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <ID> Lexeme " << yytext << " found" << endl;
    st.insert(yytext, "ID", logOut);
    tokenOut << "<ID, " << yytext << "> ";
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 58 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <CONST_INT> Lexeme " << yytext << " found" << endl;
    st.insert(yytext, "CONST_INT", logOut);
    tokenOut << "<CONST_INT, " << yytext << "> ";
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 63 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <CONST_FLOAT> Lexeme " << yytext << " found" << endl;
    st.insert(yytext, "CONST_FLOAT", logOut);
    tokenOut << "<CONST_FLOAT, " << yytext << "> ";
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 68 "1805093.l"
{
    logOut << endl << "Error at line no " << lineNo << ": Too many decimal points " << yytext << endl;
    errorNo++;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 72 "1805093.l"
{
    logOut << endl << "Error at line no " << lineNo << ": Ill formed number " << yytext << endl;
    errorNo++;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 77 "1805093.l"
{
    logOut << endl << "Error at line no " << lineNo << ": Invalid prefix on ID or invalid suffix on Number " << yytext << endl;
    errorNo++;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 81 "1805093.l"
{
    currentChar = "";
    currentExactChar = "";
    BEGIN CHAR;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 86 "1805093.l"
{
    currentChar += '\n';
    currentExactChar += "\\n";
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 90 "1805093.l"
{
    currentChar += '\t';
    currentExactChar += "\\t";
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 94 "1805093.l"
{
    currentChar += '\\';
    currentExactChar += "\\\\";
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 98 "1805093.l"
{
    currentChar += '\"';
    currentExactChar += "\\\"";
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 102 "1805093.l"
{
    currentChar += '\'';
    currentExactChar += "\\\'";    
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 106 "1805093.l"
{
    currentChar += '\a';
    currentExactChar += "\\a";
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 110 "1805093.l"
{
    currentChar += '\f';
    currentExactChar += "\\f";
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 114 "1805093.l"
{
    currentChar += '\r';
    currentExactChar += "\\r";
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 118 "1805093.l"
{
    currentChar += '\b';
    currentExactChar += "\\b";
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 122 "1805093.l"
{
    currentChar += '\v';
    currentExactChar += "\\v";
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 126 "1805093.l"
{
    currentChar += '\0';
    currentExactChar += "\\0";
}
	YY_BREAK
case YY_STATE_EOF(CHAR):
#line 130 "1805093.l"
{
    logOut << endl << "Error at line no " << lineNo << ": Unterminated character '" << currentExactChar << endl;
    errorNo++;
    BEGIN INITIAL;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 135 "1805093.l"
{
    logOut << endl << "Error at line no " << lineNo << ": Unterminated character '" << currentExactChar << endl;
    errorNo++;
    lineNo++;
    BEGIN INITIAL;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 141 "1805093.l"
{
    if ((currentChar.length() == 1) || (currentChar.length() == 0 && currentExactChar == "\\0")) {
        logOut << endl << "Line no " << lineNo << ": Token <CONST_CHAR> Lexeme '" << currentExactChar << "' found ";
        logOut << "--> <CHAR_CONST, " << currentChar << "> " << endl;
        st.insert("'"+currentExactChar+"'", "CONST_CHAR", logOut);
        logOut << endl;
        tokenOut << "<CHAR_CONST, " << currentChar << "> ";
    } else if(currentChar.length() == 0) {
        logOut << endl << "Error at line no " << lineNo << ": Empty character constant error '" << currentExactChar << "'" << endl;
        errorNo++;
    } else {
        logOut << endl << "Error at line no " << lineNo << ": Multi character constant error '" << currentExactChar << "'" << endl;
        errorNo++;
    }

    BEGIN INITIAL;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 158 "1805093.l"
{
    currentChar += yytext;
    currentExactChar += yytext;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 162 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <ADDOP> Lexeme " << yytext << " found" << endl;
    tokenOut << "<ADDOP, " << yytext << "> ";
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 166 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <MULOP> Lexeme " << yytext << " found" << endl;
    tokenOut << "<MULOP, " << yytext << "> ";
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 170 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <INCOP> Lexeme " << yytext << " found" << endl;
    tokenOut << "<INCOP, " << yytext << "> ";
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 174 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <RELOP> Lexeme " << yytext << " found" << endl;
    tokenOut << "<RELOP, " << yytext << "> ";
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 178 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <ASSIGNOP> Lexeme " << yytext << " found" << endl;
    tokenOut << "<ASSIGNOP, " << yytext << "> ";
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 182 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <logOutICOP> Lexeme " << yytext << " found" << endl;
    tokenOut << "<logOutICOP, " << yytext << "> ";
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 186 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <NOT> Lexeme " << yytext << " found" << endl;
    tokenOut << "<NOT, " << yytext << "> ";
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 190 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <LPAREN> Lexeme " << yytext << " found" << endl;
    tokenOut << "<LPAREN, " << yytext << "> ";
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 194 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <RPAREN> Lexeme " << yytext << " found" << endl;
    tokenOut << "<RPAREN, " << yytext << "> ";
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 198 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <LCURL> Lexeme " << yytext << " found" << endl;
    tokenOut << "<LCURL, " << yytext << "> ";
    st.enterScope();
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 203 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <RCURL> Lexeme " << yytext << " found" << endl;
    tokenOut << "<RCURL, " << yytext << "> ";
    st.exitScope();
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 208 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <LTHIRD> Lexeme " << yytext << " found" << endl;
    tokenOut << "<LTHIRD, " << yytext << "> ";
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 212 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <RTHIRD> Lexeme " << yytext << " found" << endl;
    tokenOut << "<RTHIRD, " << yytext << "> ";
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 216 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <COMMA> Lexeme " << yytext << " found" << endl;
    tokenOut << "<COMMA, " << yytext << "> ";
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 220 "1805093.l"
{
    logOut << endl << "Line no " << lineNo << ": Token <SEMICOLON> Lexeme " << yytext << " found" << endl;
    tokenOut << "<SEMICOLON, " << yytext << "> ";
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 224 "1805093.l"
{
    currentStr = "";
    currentExactStr = "";
    startLineNo = lineNo;
    BEGIN STR;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 230 "1805093.l"
{
    currentStr += '\n';
    currentExactStr += "\\n";
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 234 "1805093.l"
{
    currentStr += '\t';
    currentExactStr += "\\t";
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 238 "1805093.l"
{
    currentStr += '\\';
    currentExactStr += "\\\\";
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 242 "1805093.l"
{
    currentStr += '\"';
    currentExactStr += "\\\"";
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 246 "1805093.l"
{
    currentStr += '\'';
    currentExactStr += "\\\'";
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 250 "1805093.l"
{
    currentStr += '\a';
    currentExactStr += "\\a";
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 254 "1805093.l"
{
    currentStr += '\f';
    currentExactStr += "\\f";
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 258 "1805093.l"
{
    currentStr += '\r';
    currentExactStr += "\\r";
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 262 "1805093.l"
{
    currentStr += '\b';
    currentExactStr += "\\b";
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 266 "1805093.l"
{
    currentStr += '\v';
    currentExactStr += "\\v";
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 270 "1805093.l"
{
    currentStr += '\0';
    currentExactStr += "\\0";
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 274 "1805093.l"
{
    currentExactStr += "\\\r\n";
    lineNo++;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 278 "1805093.l"
{
    currentExactStr += "\\\n";
    lineNo++;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 282 "1805093.l"
{
    logOut << endl << "Error at line no " << startLineNo << ": Unterminated String \"" << currentExactStr << endl;
    errorNo++;
    lineNo++;
    BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(STR):
#line 288 "1805093.l"
{
    logOut << endl << "Error at line no " << startLineNo << ": Unterminated String \"" << currentExactStr << "\"" << endl;
    errorNo++;
    BEGIN INITIAL;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 293 "1805093.l"
{
    logOut << endl << "Line no " << startLineNo << ": Token <STRING> Lexeme \"" << currentExactStr << "\" found ";
    logOut << "--> <STRING, \"" << currentStr << "\"> " << endl;
    tokenOut << "<STRING, \"" << currentStr << "\"> ";
    BEGIN INITIAL;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 299 "1805093.l"
{
    currentStr += yytext;
    currentExactStr += yytext;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 303 "1805093.l"
{
    currExact = "";
    startLineNo = lineNo;
    BEGIN S_CMNT;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 308 "1805093.l"
{
    currExact += yytext;
    lineNo++;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 312 "1805093.l"
{
    logOut << endl << "Line no " << startLineNo << ": Token <COMMENT> Lexeme //" << currExact << " found" << endl;
    lineNo++;
    BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(S_CMNT):
#line 317 "1805093.l"
{
    logOut << endl << "Line no " << startLineNo << ": Token <COMMENT> Lexeme //" << currExact << " found" << endl;
    BEGIN INITIAL;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 321 "1805093.l"
{
    currExact += yytext;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 324 "1805093.l"
{
    currExact = "";
    startLineNo = lineNo;
    BEGIN M_CMNT;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 329 "1805093.l"
{
    logOut << endl << "Line no " << startLineNo << ": Token <COMMENT> Lexeme /*" << currExact << "*/ found" << endl;
    BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(M_CMNT):
#line 333 "1805093.l"
{
    logOut << endl << "Error at line no " << startLineNo << ": Unterminated Comment /*" << currExact << endl;
    errorNo++;
    BEGIN INITIAL;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 338 "1805093.l"
{
    currExact += yytext;
    lineNo++;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 342 "1805093.l"
{
    currExact += yytext;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 345 "1805093.l"
{
    logOut << endl << "Error at line no " << lineNo << ": Unrecognized character '" << yytext << "'" << endl;
    errorNo++;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 351 "1805093.l"
ECHO;
	YY_BREAK
#line 1348 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 174 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 174 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 173);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 351 "1805093.l"

int main(int argc, char** argv) {
    if (argc < 2) {
        cout << "Specify input file" << endl;
    } else {
        logOut.open("1805093_log.txt");
        tokenOut.open("1805093_token.txt");

        yyin = fopen(argv[1], "r");
        yylex();
        fclose(yyin);   

        st.printSymbols(logOut);
        logOut << endl;
        logOut << "Total lines: " << lineNo << endl;
        logOut << "Total errors: " << errorNo << endl;

        logOut.close();
        tokenOut.close();
    }
    

    return 0;
}
